#!/usr/bin/env python3
"""扫描 projects/ 下的 HTML 文件, 生成 projects/index.html 导航页"""
import os, re, json
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJ = os.path.join(ROOT, "projects")

# 文件名 -> 标题/描述的映射 (自动从 HTML <title> 提取, 可在此覆盖)
TITLES = {
    "xinjiang-tour-map-amap.html": ("新疆南疆旅游路线 · 高德地图", "高德 JSAPI v2.0 交互地图，20个景点分色标记+3条示意线路"),
    "xinjiang-tour-map-osm.html": ("新疆南疆旅游路线 · OSM地图", "OpenStreetMap 版交互地图，无需Key，可作对照"),
    "xinjiang-tour-route.kml": ("新疆南疆旅游路线 · KML数据", "可导入高德/Google地图App的KML文件"),
}

def extract_title(path):
    try:
        with open(path, encoding="utf-8") as f:
            m = re.search(r"<title>(.*?)</title>", f.read(), re.S)
            return m.group(1).strip() if m else None
    except Exception:
        return None

items = []
for fn in sorted(os.listdir(PROJ)):
    if fn.startswith("."):
        continue
    fp = os.path.join(PROJ, fn)
    if os.path.isfile(fp):
        if fn == "index.html":
            continue
        ext = os.path.splitext(fn)[1].lower()
        if ext not in (".html", ".kml", ".kmz", ".pdf", ".md"):
            continue
        title, desc = TITLES.get(fn, (None, None))
        if not title:
            title = extract_title(fp) or fn
        if not desc:
            desc = ""
        mtime = datetime.fromtimestamp(os.path.getmtime(fp)).strftime("%Y-%m-%d")
        items.append({"file": fn, "title": title, "desc": desc, "date": mtime, "ext": ext})

cards = "\n".join(
    f'''      <a class="card" href="{it["file"]}" target="_blank">
        <div class="card-title">{it["title"]}</div>
        <div class="card-desc">{it["desc"] or "点击打开"}</div>
        <div class="card-meta">{it["date"]} · {it["ext"].lstrip(".").upper()}</div>
      </a>''' for it in items)

html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Projects · Wang Jun</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif;
         background:#0d1117; color:#c9d1d9; min-height:100vh; }}
  .wrap {{ max-width:960px; margin:0 auto; padding:2.5rem 1.5rem; }}
  header {{ margin-bottom:2rem; }}
  header a {{ color:#58a6ff; text-decoration:none; font-size:0.9rem; }}
  h1 {{ font-size:1.8rem; color:#f0f6fc; margin:0.5rem 0; }}
  .sub {{ color:#8b949e; font-size:1rem; margin-bottom:1.5rem; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr)); gap:1rem; }}
  .card {{ display:block; background:#161b22; border:1px solid #30363d; border-radius:10px;
          padding:1.1rem 1.2rem; text-decoration:none; color:inherit;
          transition:border-color .2s, transform .2s; }}
  .card:hover {{ border-color:#58a6ff; transform:translateY(-2px); }}
  .card-title {{ font-size:1.05rem; font-weight:600; color:#f0f6fc; margin-bottom:0.4rem; }}
  .card-desc {{ font-size:0.88rem; color:#8b949e; line-height:1.5; margin-bottom:0.6rem; }}
  .card-meta {{ font-size:0.78rem; color:#6e7681; }}
  footer {{ margin-top:2.5rem; text-align:center; color:#6e7681; font-size:0.8rem; }}
</style>
</head>
<body>
<div class="wrap">
  <header>
    <a href="../">← 返回主页</a>
    <h1>📁 Projects</h1>
    <p class="sub">我的 HTML 作品集 · 共 {len(items)} 个项目 · 自动生成于 {datetime.now().strftime("%Y-%m-%d %H:%M")}</p>
  </header>
  <div class="grid">
{cards}
  </div>
  <footer>Generated by build_index.py · GitHub Pages</footer>
</div>
</body>
</html>"""

with open(os.path.join(PROJ, "index.html"), "w", encoding="utf-8") as f:
    f.write(html)
print(f"✅ 索引生成: {len(items)} 个项目 -> projects/index.html")
